name: pr_website
on:
  pull_request:
    branches: main

jobs:
  build:
    name: Build website with rmarkdown
    runs-on: ubuntu-latest
    

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:              
          tinytex: true   
      - name: Generate slides
        run: "quarto render"
