name: website
on:
  push:
    branches:
      - main

name: Render and Publish

jobs:
  build-deploy:
    name: Build website with quarto
    runs-on: ubuntu-latest
    
    permissions: 
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
                 # To install LaTeX to build PDF book 
          tinytex: true 
   
       - name: Setup R
         uses: r-lib/actions/setup-r@v2  
          
      - name: Publish to GitHub Pages (and render) 
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          publish_dir: ./_site
          env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           
           
           
           
          

